---
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.59.0/hugo_0.59.0_Linux-64bit.deb
  - sudo dpkg -i hugo_0.59.0_Linux-64bit.deb

script:
  - hugo
env:
  global:
    # GITHUB_TOKEB
    secure: "e3mOk7ebEZFIEU4knNtUgkLmzn/OGjJRGS7e8ny1eTnb/NpL7YXbUIu6sgHhj0ItxIwRU0Eo7I4PzW7M+YtVcCT7Qr6UjNn9HZCka+7QKI2zhhu4nxJ6zL8JdRvuUEfnPKt66Tm1zfCn4Ain8B6WQMP1tjadkfMUKWqvg997lfk="
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
      branch: master