# This is a basic workflow to help you get started with Actions

name: Publish to medium

on:
  push:
    branches: [ master ]

jobs:
  hugo_to_medium_job:
    runs-on: ubuntu-latest
    name: hugo-to-medium
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Hugo To Medium step 
        uses: pr4k/Hugo-to-Medium@master
        id: hello
        env:
          APP_ID: ${{secrets.APP_ID}} # https://medium.com/me/applications
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}} # https://medium.com/me/settings
          APP_SECRET: ${{secrets.APP_SECRET}} # https://medium.com/me/applications
          BLOG_DIR: content/posts
